services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    ports:
      - '${PORT_DB}:${PORT_DB}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
